CREATE TABLE Pessoa (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Nome NVARCHAR(100) NOT NULL,
    DataNascimento DATE NOT NULL,
    Cpf NVARCHAR(11) NOT NULL
);

CREATE TABLE Telefone (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NumeroTelefone NVARCHAR(10) NULL,
    IdPessoa UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_PessoaTelefone FOREIGN KEY (IdPessoa) REFERENCES Pessoa(Id)
);